// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeDay3.Data;

#nullable disable

namespace PracticeDay3.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260603065955_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticeDay3.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jahir Villa",
                            Price = 65324789.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Raza Villa",
                            Price = 732889.90000000002
                        });
                });

            modelBuilder.Entity("PracticeDay3.Models.VillaAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("VillasAmenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Velcony",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plambing Service",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Private Pool",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pond",
                            VillaId = 1
                        });
                });

            modelBuilder.Entity("PracticeDay3.Models.VillaAmenity", b =>
                {
                    b.HasOne("PracticeDay3.Models.Villa", "Villa")
                        .WithMany("VillaAmenities")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("PracticeDay3.Models.Villa", b =>
                {
                    b.Navigation("VillaAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
